config/routes.rb
Rails.application.routes.draw do
  get 'hallway/index'
  get 'hallway/show'
  resources :scrollzs
  resources :games
  resources :choices
  resources :stages

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get "/pages/:page"=> "pages#show"
root "pages#show", page: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :stage, class_name: "Stage"



end 

app/models/event.rb
class Event < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
belongs_to :user

belongs_to :stage

  validates :user_id, presence: true

end

app/models/hallway.rb
class Hallway < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
 def initialize
    @image = Gosu::Image.new("media/starfighter.bmp")
    @x = @y = @vel_x = @vel_y = @angle = 0.0
    @score = 0
  end

  def warp(x, y)
    @x, @y = x, y
  end

  def turn_left
    @angle -= 4.5
  end

  def turn_right
    @angle += 4.5
  end

  def accelerate
    @vel_x += Gosu::offset_x(@angle, 0.5)
    @vel_y += Gosu::offset_y(@angle, 0.5)
  end

  def move
    @x += @vel_x
    @y += @vel_y
    @x %= 640
    @y %= 480

    @vel_x *= 0.95
    @vel_y *= 0.95
  end

  def draw
    @image.draw_rot(@x, @y, 1, @angle)
  end
end

end

app/models/scrollz.rb
class Scrollz < ApplicationRecord
  has_many :stages
  has_many :choices, through: :stages

  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates :title, uniqueness: true, presence: true
  validates :description, presence: true



  def murder(stage_node)
    html = ''
    html += "<ul>" if first_chapter(chapter_node)
    html += "<li><a href='/scrollz/" + "#{chapter_node.scrollz_id}" + "/stages/#{stage_node.id}/choices/new'> #{first_3_words(stage_node)}</a>"
    moreChoices?(stage_node) ? html += "<ul>" : html += "</li>"
    if stage_node.parent_choice_id != nil && !moreChoices?(stage_node)
      html += "</ul>" if end_of_row?(stage_node)
    end
    stage_node.choices.each do |choice|
      next_stage = Stage.where(parent_choice_id: choice.id).first
      next_html = !!(next_stage) ? murder(next_stage) : "</ul></li>"
      html += next_html
    end
    html
  end

  def create_scene(stage_node)
    return '' if stage_node.nil?
    html = murder(stage_node)
    html = html.chomp('</ul>')
    html += "</ul></li>" * calculate_uls(html)
    html += "</ul>"
  end

  def calculate_uls(html)
    (count_opening_uls(html) - 1) - count_closing_uls(html)
  end

  def count_opening_uls(html)
    html.scan(/<ul>/).size
  end

  def count_closing_uls(html)
    html.scan(/<\/ul>/).size
  end

  # return true if first chapter
  def first_stage(stage)
  stage.id === self.stages.first.id
  end

  def last_stage(stage)
  stage.id === self.stages.last.id
  end

  #options check
  def moreChoices?(check_stage)
    find_children_stage(check_stage, false) != []
  end

  def find_children_stage(stage, array_of_ids)
    @choices = Choice.where(stage_id: stage.id)
    find_stages_from_choices(@choices, array_of_ids)
  end

  def find_stages_from_choices(array_of_choices, array_of_ids)
    stages= []
    if array_of_ids == false
      array_of_choices.each do |choice|
        stages << Stages.where(parent_choice_id: choice.id)
      end
    else
      array_of_choices.each do |choice|
        stages<< Stage.where(parent_choice_id: choice.id).pluck(:id)
      end
    end
    stages.flatten
  end

  def end_of_row?(stage)
    choice_found = find_parent_choice(stage)
    parent_stage = find_parent_stage(choice_found)
    if parent_stage!= nil
      children_stage_ids = find_children_stages(parent_stage, true)
      highest_stage_id(children_stage_ids, stage)
    else
      return false
    end
  end
#is this the end lol
  def highest_stage_id(children_stage_ids, current_stage)
    children_stage_ids.max === current_stage.id
  end


  def find_parent_choice(stage)
    Choice.find(stage.parent_choice_id)
  end

  def find_parent_chapter(choice)
    return nil if choice.stage_id.nil?
  Stage.find(choice.stage_id)
  end

  def first_3_words(stage)
    stage.description.split(" ").slice(0, 3).join(" ").concat("...")
  end

end

app/models/stage.rb
class Stage < ApplicationRecord



has_many :choices, dependent: :destroy



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




  has_many :games
  has_many :stages, through: :games
  has_many :choices, through: :games
end

app/models/window.rb
class Window < ApplicationRecord
require 'gosu'


  def initialize
    super 640, 480
    self.caption = "Gosu Tutorial Game"
  end

  def update
  end

  def draw
@background_image.draw(0, 0, 0)
  end
end

window = GameWindow.new
window.show
end

app/controllers/games_controller.rb
class GamesController < ApplicationController


def delete
game = Game.where(scrollz_id: params[:scrollz_id], user_id: current_user.id).first
    game.destroy
    @first_stage = Stage.where(scrollz_id: params[:scrollz_id]).first
    redirect_to
  end
end

app/controllers/scrollzs_controller.rb
class ScrollzsController < ApplicationController
  before_action  only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, :except => [:index, :show]

  # GET /scrollzs
  # GET /scrollzs.json
  def index
    @scrollz = Scrollz.all
  end


  def show

  end


  def new

  end




  def create
    @scrollz = Scrollz.new(scrollz_params)
    @scrollz.user_id = current_user.id
    if @scrollz.save
      @scrollz_id = @scrollz.id
      redirect_to new_scrollz_path_stage_path(@scrollz)
    else
      flash[:error] = "????"
      redirect_to new_scrollz_path
    end
  end

  def design
    @scrollz = Scrollz.find(params[:scrollz_id])
    is_the_user_the_owner(@scrollz, current_user)
    @stages = Stages.where(scrollz_id: @scrollz.id)
    unless @stages[0]
      redirect_to new_scrollz_path_stage_path(@scrollz)
    end
    @scrollz_id = @scrollz.id
  end


  private

  def scrollz_params
    params.require(:scrollz).permit(:title, :instruction)
  end
##ensure the user signed in
  def is_the_user_the_owner(scrollz, user)
    if scrollz.user_id != user.id
      flash[:notice] = "?"
      redirect_to scrollz_path(@scrollz)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hallway_helper.rb
module HallwayHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/scrollzs_helper.rb
module ScrollzsHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/windows_helper.rb
module WindowsHelper
end

app/views/scrollzs/edit.html.erb
<h1>Editing Scrollz</h1>

<%= render 'form', scrollz: @scrollz %>

<%= link_to 'Show', @scrollz %> |
<%= link_to 'Back', scrollzs_path %>

app/views/scrollzs/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Adventure</title>

  </head>
  <body>

    <div class="main">

    </div>

    <div class="scrollz">
        <% @scrollzs.each do |scrollz|%>
          <div class="scrollz">
            <%= link_to "#{scrollz.title}", scrollz_path(scrollz.id), class: "scrollz_title" %>

            </div>
          </div>
        <% end %>
    </div>

  </body>
</html>

app/views/scrollzs/moving.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <div id="cyo">
      <h1>Design your OWN</h1>
    </div>

    <div id="murder">
      <%= @scrollz.title %><br>
    </div>

    <div class="moving-container">


      <div class="hoops">
        <%= @scrollz.create_hoop(@scrollz.stages.first).html_safe %>
      </div>

      <div class="crud_container">

        <% @stages.each do |stage| %>
        <div class="design_stage">
          <%= stage.description %><br>
        </div>

        <div class="update_delete_container">
          <%= link_to "Update Stage",  edit_scrollz_chapter_path(@scrollz, chapter.id), id: "design_link_update"%>

        </div>

        <% end %>
      </div>

    </div>
  </body>
</html>

app/views/scrollzs/new.html.erb
  <div class="stage1">


    <div id="chap1" >
        <%= audio_tag "rain.mp3", :id => "rain", :onload => "playSound()" %>
    <%= image_tag "cloud.png", :style => "width: 50%;left: -16%;position: relative;top: 102px;"%>
      <br><br><br><br><br>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>


    <div class="form_play">
      <% if @first_stage %>
        <%= link_to "Play", scrollz_stage_path(@scrollz, @first_stage), class: "start_button"%>
      <% end %>
      <% if current_user && @scrollz_id == current_user.id %>

      <% end %>
    </div>
  </body>
</html>


    </div>

app/views/scrollzs/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="description">
      <%= @scrollz.description %>
    </div>
    <div class="form_play">
      <% if @first_stage %>
        <%= link_to "Play", scrollz_stage_path(@scrollz, @first_stage), class: "start_button"%>
      <% end %>
      <% if current_user && @scrollz.user_id == current_user.id %>
        <%= link_to "Edit", scrollz_create_path(@scrollz), class: "start_button" %>
      <% end %>
    </div>
  </body>
</html>

app/views/scrollzs/stuff.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <%= form_for [@scrollz, @stage, @choice] do |f| %>
      <%= f.fields_for :choice, [Choice.new] do |choice| %>
        <%= choice.text_field :option %>
      <% end %>
    <%= f.submit %>
    <% end %>
  </body>
</html>